#!/bin/sh

if command -v udevd >/dev/null; then
	udevd -d
	udevadm trigger -c add -t subsystems
	udevadm trigger -c add -t devices
	udevadm trigger -c change -t devices
	udevadm settle
elif command -v mdev >/dev/null; then
	mdev -s
	mdev -df & mdev_pid=$!
	[ -x /bin/dmsetup ] && dmsetup mknodes
fi
